trailingComma: "es5"
tabWidth: 2
semi: false
singleQuote: false
importOrder: ["<THIRD_PARTY_MODULES>", "^@wr/(.*)$", "^[./]"]
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrderParserPlugins: ["typescript", "decorators-legacy", "jsx", "classProperties"]
printWidth: 140
endOfLine: "lf"
arrowParens: "always"
plugins:
  - "@trivago/prettier-plugin-sort-imports"
  - "prettier-plugin-tailwindcss"
