export default {
  sidemenu: {
    newChat: "New Chat",
    chat: "Chat",
    agents: "Agents",
    folder: "Folder",
    setting: "Setting",
    mode: {
      light: "Light",
      dark: "Dark",
    },
  },
  setting: {
    title: "Settings",
    description: "Manage your organization settings.",
    organization: {
      title: "Organization",
      name: "Name",
    },
    aiVendor: {
      title: "AI Vendor",
      currentVendor: "Current Vendor",
      auto: "Auto (use available vendor)",
      openai: "OpenAI",
      anthropic: "Anthropic",
      google: "Google",
    },
    userManagement: {
      title: "User Management",
      goToList: "Go to user list",
    },
    accessGroup: {
      title: "Access Group Management",
      goToList: "Go to access group list",
    },
    agentSettings: {
      title: "Agent Settings",
      name: "Name",
      description: "Description",
      coordinator: {
        name: "Coordinator",
        description: "An user facing agent",
      },
      heavy: {
        name: "Heavy",
        description: "A more sophisticated model to think deeply.",
      },
    },
    tokenUsage: {
      title: "Token Usage",
      date: "Date",
      model: "Model",
      inputCached: "Input token (Cached)",
      output: "Output token",
      cost: "Cost",
    },
  },
  account: {
    title: "Account",
    description: "Manage your user settings.",
    userData: {
      title: "User data",
      name: "Name",
      email: "Email",
      role: "Role",
    },
    signout: {
      title: "Signout",
      button: "Sign Out",
      error: "Failed to sign out",
    },
  },
  common: {
    save: "Save",
    cancel: "Cancel",
    ok: "OK",
    failed: "Failed",
    error: "Error",
    cannotBeUndone: "This action cannot be undone.",
    noDataAvailable: "No data available.",
    goBackToHome: "Go back to home",
    loading: "Loading...",
    invalidInput: "Invalid input",
    validation: {
      required: "Required",
      maxLength: "Exceeds maximum length",
      passwordMinLength: "Password must be at least 8 characters long",
      invalidEmail: "Please enter a valid email address",
    },
  },
  errorPage: {
    notFound: "404 Not Found",
    forbidden: "403 Forbidden",
    serverError: "500 Internal Server Error",
  },
  signin: {
    appName: "WorkingRoom",
    title: "Sign In",
    emailLabel: "Email",
    emailPlaceholder: "email",
    passwordLabel: "Password",
    passwordPlaceholder: "password",
    submit: "Sign In",
    noAccount: "Don't have an account? Sign Up",
    failed: "Sign In Failed",
  },
  signup: {
    appName: "WorkingRoom",
    title: "Sign Up",
    emailLabel: "Email",
    emailPlaceholder: "email",
    submit: "Sign Up",
    alreadyHaveAccount: "Already have an account? Sign In",
    successTitle: "Sign Up Success",
    successCredentials: "Your credentials have been downloaded. \nPlease check the downloaded file for your initial password and sign in.",
    successEmail: "Please check your email for the sign in link.",
    failed: "Sign Up Failed",
  },
  home: {
    title: "Your Chats",
    description: "Start a new chat or continue with your existing chats.",
    startFirstChat: "Start your first chat",
    newChat: "New Chat",
    searchChatPlaceholder: "Search chat",
    chatNotFound: "Chat not found",
  },
  chat: {
    placeholder: "Chat with your assistant",
    inputPlaceholder: "Type your message here...",
    currentDirectory: "Current directory",
    changeDirectory: "Change directory",
    privateFolder: "private",
    moreFileSingular: "and {0} more file",
    moreFilePlural: "and {0} more files",
  },
  tree: {
    description: "Browse your files and folders.",
    uploadTitle: "Upload",
    uploadSuccess: "Files uploaded successfully.",
    uploadFailed: "Failed to upload files.",
    dropToUpload: "Drop files here to upload",
  },
  accessGroup: {
    createFailed: "Failed to create access group.",
    editFailed: "Failed to edit access group.",
    deleteFailed: "Failed to delete access group.",
    chatDirNotAllowed: "Chat directories cannot be added to access groups",
    privateDirNotAllowed: "Private directories cannot be added to access groups",
    personalGroupNotDeletable: "Personal access groups cannot be deleted",
    personalGroupNotEditable: "Personal access groups cannot have resources or users edited",
    ownerGroupNotEditable: "Owner access groups cannot have resources or users edited",
  },
  user: {
    editFailed: "Failed to edit user.",
    cannotEditUser: "Cannot edit user.",
  },
  tenant: {
    cannotInviteUser: "Cannot invite user.",
    inviteUserFailed: "Failed to invite user.",
    cannotEditTenant: "Cannot edit tenant.",
    editTenantFailed: "Failed to edit tenant.",
    cannotEditAiVendor: "Cannot edit AI vendor.",
    editAiVendorFailed: "Failed to edit AI vendor.",
    aiVendorNotConfigured: "The selected AI vendor is not configured. Please set the required API key.",
    cannotDeleteUser: "Cannot delete user.",
    deleteUserFailed: "Failed to delete user.",
    cannotResetPassword: "Cannot reset password.",
    resetPasswordFailed: "Failed to reset password.",
    cannotChangeRole: "Cannot change role.",
    changeRoleFailed: "Failed to change role.",
  },
  file: {
    download: "Download",
    edit: "Edit",
    save: "Save",
    cancelEdit: "Cancel",
    backToDirectory: "Back to directory",
    createdAt: "Created at {0}",
    emptyFile: "Empty file",
    noPdfPlugin: "It appears you don't have a PDF plugin for this browser. You can",
    downloadPdf: "click here to download the PDF file.",
    unsupportedFileType: "Unsupported file type:",
    notFound: "File not found",
    history: {
      title: "File History",
      loading: "Loading...",
      noHistory: "No history available.",
      current: "current",
    },
    list: {
      noFiles: "No files found",
      name: "Name",
      type: "Type",
      modified: "Modified",
      back: "back",
      newFolder: "New Folder",
      newFile: "New File",
      rename: "Rename",
      delete: "Delete",
      copyTitle: "Copy",
      copySuccess: "File copied successfully.",
      moveTitle: "Move",
      moveSuccess: "File moved successfully.",
      moveInvalid: "Invalid file or target folder.",
      accessGroup: "Create Access Group",
      dragItems: "{0} items",
    },
    errors: {
      uploadFailed: "Failed to upload file.",
      uploadPermissionDenied: "You do not have permission to upload files to this location.",
      uploadToChatFailed: "Failed to upload file to chat.",
      deleteFailed: "Failed to delete file.",
      cannotDeleteRoot: "You cannot delete root directory.",
      cannotDeletePrivate: "You cannot delete private directories.",
      cannotDeleteChat: "You cannot delete chat directories.",
      cannotDeleteShared: "You cannot delete shared root directories.",
      createDirectoryFailed: "Failed to create directory.",
      createDirectoryPermissionDenied: "You do not have permission to create a directory in this location.",
      renameFailed: "Failed to rename file.",
      renamePermissionDenied: "You do not have permission to rename this file.",
      copyFailed: "Failed to copy file.",
      cannotCopyDirectory: "You cannot copy a directory.",
      moveFailed: "Failed to move file.",
      movePermissionDenied: "You do not have permission to move this file or folder.",
      restoreHistoryFailed: "Failed to restore file history.",
      restoreHistoryPermissionDenied: "You do not have permission to restore this file history.",
      updateContentFailed: "Failed to save file.",
      updateContentPermissionDenied: "You do not have permission to edit this file.",
      createFileFailed: "Failed to create file.",
      accessDenied: "You don't have access to this file.",
      folderAccessDenied: "You don't have access to this folder.",
      contentNotFound: "The content to be replaced does not exist in the file.",
      cannotMoveIntoDescendant: "Cannot move a directory into its own descendant.",
      cannotMoveIntoFile: "Cannot move a file/directory into a file.",
      cannotMoveChat: "You cannot move a chat directory.",
    },
  },
  modal: {
    userEdit: {
      title: "Edit User",
      userName: "User Name",
      userNamePlaceholder: "Enter user name",
      language: "Language",
      english: "English",
      japanese: "日本語",
      failed: "Failed",
    },
    userInvite: {
      title: "Invite User",
      emailLabel: "Email",
      emailPlaceholder: "user@workingroom.io",
      invite: "Invite",
      failed: "Failed",
    },
    userChangeRole: {
      title: "Edit Tenant",
      userRole: "User Role",
      admin: "Admin",
      member: "Member",
      roleUnchanged: "Role is unchanged",
      failed: "Failed",
    },
    userDelete: {
      title: "Delete User",
      confirm: "Are you sure you want to delete this user?",
      failed: "Failed",
    },
    userResetPassword: {
      title: "Reset User Password",
      confirm: "Are you sure you want to reset the password for this user?",
      failed: "Failed",
    },
    tenantEdit: {
      title: "Edit Tenant",
      tenantName: "Tenant Name",
      tenantNamePlaceholder: "Enter tenant name",
      nameUnchanged: "Name is unchanged",
      failed: "Failed",
    },
    tenantAiVendorEdit: {
      title: "Edit AI Vendor",
      vendor: "AI Vendor",
      auto: "Auto (use available vendor)",
      openai: "OpenAI",
      anthropic: "Anthropic",
      google: "Google",
      failed: "Failed",
    },
    directoryCreate: {
      title: "Create Directory",
      directoryName: "Directory Name",
      directoryNamePlaceholder: "Enter directory name",
      create: "Create",
      failed: "Failed",
    },
    fileCreate: {
      title: "New File",
      fileName: "File Name",
      fileNamePlaceholder: "e.g. notes.md",
      fileType: "File Type",
      markdown: "Markdown (.md)",
      text: "Plain Text (.txt)",
      create: "Create",
      failed: "Failed",
    },
    directoryDelete: {
      title: "Delete Directory",
      confirm: "Are you sure you want to delete the directory?",
      allFilesDeleted: "All files under this directory will also be deleted.",
      failed: "Failed",
    },
    fileRename: {
      title: "Rename File",
      fileName: "File Name",
      fileNamePlaceholder: "Enter file name",
      sameAsCurrentName: "Same as current name",
      failed: "Failed",
    },
    fileDelete: {
      title: "Delete File",
      confirmSingular: "Are you sure you want to delete this file?",
      confirmPlural: "Are you sure you want to delete these files?",
      failed: "Failed",
    },
    fileHistoryRestore: {
      title: "Restore File History",
      confirm: "Are you sure you want to restore the file history?",
      failed: "Failed",
    },
    chatDelete: {
      title: "Delete Chat",
      confirm: "Are you sure you want to delete this chat?",
      error: "Error",
    },
    initializePassword: {
      title: "Password Initialization",
      password: "Password",
      passwordPlaceholder: "password",
      confirmPassword: "Confirm Password",
      confirmPasswordPlaceholder: "confirm password",
      passwordMismatch: "Passwords do not match",
      initialize: "Initialize Password",
      error: "Error",
    },
    accessGroupCreate: {
      title: "Create Access Group",
      description: "Creating an access group for {0}.",
      permissionNote: "You can manage the permissions of this group after creation.",
      groupName: "Group Name",
      groupNamePlaceholder: "e.g. Marketing Team",
      groupNameRequired: "Group name is required",
      groupNameMaxLength: "Group name must be less than 50 characters",
      descriptionLabel: "Description (optional)",
      descriptionPlaceholder: "Enter group description",
      success: "Success",
      successMessage: 'Access group "{0}" has been created.',
      failed: "Failed",
    },
    accessGroupDelete: {
      title: "Delete Access Group",
      confirm: "Are you sure you want to delete the following access group?",
      failed: "Failed",
    },
    accessGroupResourceDelete: {
      title: "Delete Resource from Access Group",
      confirm: "Are you sure you want to remove this resource from the access group?",
    },
    accessGroupUserDelete: {
      title: "Delete User from Access Group",
      confirm: "Are you sure you want to remove this user from the access group?",
    },
    agentDelete: {
      title: "Delete Agent",
      confirm: 'Are you sure you want to delete the agent "{0}"?',
      failed: "Failed to delete agent",
    },
    fileSelect: {
      title: "Select Folder",
      name: "Name",
      back: "back",
      noFiles: "No files found",
      select: "Select",
      close: "Close",
    },
    userSelect: {
      title: "Select User",
      name: "Name",
      email: "Email",
      role: "Role",
      noUsers: "No users found",
      searchPlaceholder: "Search users by name or email",
    },
  },
  settingUser: {
    title: "User list",
    description: "Manage your user",
    addUser: "Add User",
    actions: {
      resetPassword: "Reset Password",
      changeRole: "Change Role",
      delete: "Delete",
    },
    headers: {
      name: "Name",
      email: "Email",
      role: "Role",
      createdAt: "Created At",
    },
  },
  settingAccessGroupList: {
    title: "Access Group list",
    description: "Manage organization access groups",
    headers: {
      name: "Name",
      type: "Type",
      description: "Description",
    },
  },
  settingAccessGroup: {
    title: "Access Group Management",
    description: "Manage access group",
    editTitle: "Edit Access Group",
    edit: "Edit",
    delete: "Delete",
    addResource: "Add Resource",
    addUser: "Add User",
    fileAdded: "File added to access group",
    userAdded: "User added to access group",
    updated: "Access group updated",
    yes: "Yes",
    no: "No",
    details: {
      title: "Details",
      name: "Name",
      description: "Description",
      type: "Type",
      read: "Read",
      write: "Write",
      personal: "Personal",
      group: "Group",
    },
    resources: {
      title: "Resources in this access group",
      name: "Name",
      type: "Type",
    },
    users: {
      title: "Users in this access group",
      name: "Name",
      email: "Email",
    },
  },
  agent: {
    list: {
      title: "Agent list",
      description: "List of agents you have created",
      name: "Name",
      tier: "Tier",
      noData: "-",
      create: "Create",
      delete: "Delete",
    },
    create: {
      title: "Create Agent",
      description: "Create a new agent for your workspace.",
      success: "Success",
      created: "Agent created successfully",
      sectionDescriptions: "Agent Descriptions",
      sectionPrompt: "Prompt",
      fields: {
        name: "Name",
        namePlaceholder: "e.g. Company rule agent",
        tier: "Model Tier",
        workingFolder: "Working Folder",
        workingFolderPlaceholder: "Select a working folder",
        description: "Description",
        descriptionPlaceholder: "e.g. An agent that helps manage company rules",
        descriptionForAgent: "Description for Agent",
        descriptionForAgentPlaceholder: "e.g. An agent that helps manage company rules",
        prompt: "System prompt",
        promptPlaceholder: "e.g. Generate a summary of company rules",
      },
      validation: {
        tierRequired: "Model tier is required",
        tierInvalid: "Invalid model tier",
      },
    },
    detail: {
      title: "Agent",
      defaultDescription: "Agent details",
      edit: "Edit",
      sectionDescriptions: "Agent Descriptions",
      sectionDescriptionForAgent: "Description for Agent",
      sectionPrompt: "System prompt",
      fields: {
        name: "Name",
        tier: "Model Tier",
        workingFolder: "Working Folder",
        description: "Description",
        noData: "-",
      },
    },
    edit: {
      title: "Edit Agent",
      description: "Update your agent settings.",
      updated: "Agent updated successfully",
      save: "Save",
    },
  },
}
