export default {
  sidemenu: {
    newChat: "New Chat",
    chat: "Chat",
    folder: "Folder",
    setting: "Setting",
    mode: {
      light: "Light",
      dark: "Dark",
    },
  },
  setting: {
    title: "Settings",
    description: "Manage your organization settings.",
    organization: {
      title: "Organization",
      name: "Name",
    },
    userManagement: {
      title: "User Management",
      goToList: "Go to user list",
    },
    accessGroup: {
      title: "Access Group Management",
      goToList: "Go to access group list",
    },
    agentSettings: {
      title: "Agent Settings",
      name: "Name",
      description: "Description",
      coordinator: {
        name: "Coordinator",
        description: "An user facing agent",
      },
      heavy: {
        name: "Heavy",
        description: "A more sophisticated model to think deeply.",
      },
    },
    tokenUsage: {
      title: "Token Usage",
      date: "Date",
      model: "Model",
      inputCached: "Input token (Cached)",
      output: "Output token",
    },
  },
  account: {
    title: "Account",
    description: "Manage your user settings.",
    userData: {
      title: "User data",
      name: "Name",
      email: "Email",
      role: "Role",
    },
    signout: {
      title: "Signout",
      button: "Sign Out",
      error: "Failed to sign out",
    },
  },
  common: {
    save: "Save",
    cancel: "Cancel",
    ok: "OK",
    failed: "Failed",
    error: "Error",
    cannotBeUndone: "This action cannot be undone.",
    noDataAvailable: "No data available.",
    goBackToHome: "Go back to home",
    loading: "Loading...",
    validation: {
      required: "Required",
      passwordMinLength: "Password must be at least 8 characters long",
    },
  },
  errorPage: {
    notFound: "404 Not Found",
    forbidden: "403 Forbidden",
    serverError: "500 Internal Server Error",
  },
  signin: {
    appName: "WorkingRoom",
    title: "Sign In",
    emailLabel: "Email",
    emailPlaceholder: "email",
    passwordLabel: "Password",
    passwordPlaceholder: "password",
    submit: "Sign In",
    noAccount: "Don't have an account? Sign Up",
    failed: "Sign In Failed",
  },
  signup: {
    appName: "WorkingRoom",
    title: "Sign Up",
    emailLabel: "Email",
    emailPlaceholder: "email",
    submit: "Sign Up",
    alreadyHaveAccount: "Already have an account? Sign In",
    successTitle: "Sign Up Success",
    successCredentials: "Your credentials have been downloaded. \nPlease check the downloaded file for your initial password and sign in.",
    successEmail: "Please check your email for the sign in link.",
    failed: "Sign Up Failed",
  },
  home: {
    title: "Your Chats",
    description: "Start a new chat or continue with your existing chats.",
    startFirstChat: "Start your first chat",
    newChat: "New Chat",
  },
  chat: {
    placeholder: "Chat with your assistant",
    inputPlaceholder: "Type your message here...",
    moreFileSingular: "and {0} more file",
    moreFilePlural: "and {0} more files",
  },
  tree: {
    description: "Browse your files and folders.",
    uploadTitle: "Upload",
    uploadSuccess: "Files uploaded successfully.",
    uploadFailed: "Failed to upload files.",
    dropToUpload: "Drop files here to upload",
  },
  accessGroup: {
    createFailed: "Failed to create access group.",
    deleteFailed: "Failed to delete access group.",
    chatDirNotAllowed: "Chat directories cannot be added to access groups",
    privateDirNotAllowed: "Private directories cannot be added to access groups",
    personalGroupNotDeletable: "Personal access groups cannot be deleted",
  },
  file: {
    backToDirectory: "Back to directory",
    createdAt: "Created at {0}",
    noPdfPlugin: "It appears you don't have a PDF plugin for this browser. You can",
    downloadPdf: "click here to download the PDF file.",
    unsupportedFileType: "Unsupported file type:",
    notFound: "File not found",
    history: {
      title: "File History",
      loading: "Loading...",
      noHistory: "No history available.",
      current: "current",
    },
    list: {
      noFiles: "No files found",
      name: "Name",
      type: "Type",
      modified: "Modified",
      back: "back",
      newFolder: "New Folder",
      rename: "Rename",
      delete: "Delete",
      copyTitle: "Copy",
      copySuccess: "File copied successfully.",
      moveTitle: "Move",
      moveSuccess: "File moved successfully.",
      moveInvalid: "Invalid file or target folder.",
      accessGroup: "Create Access Group",
      dragItems: "{0} items",
    },
    errors: {
      uploadFailed: "Failed to upload file.",
      uploadPermissionDenied: "You do not have permission to upload files to this location.",
      uploadToChatFailed: "Failed to upload file to chat.",
      deleteFailed: "Failed to delete file.",
      cannotDeleteRoot: "You cannot delete root directory.",
      cannotDeletePrivate: "You cannot delete private directories.",
      cannotDeleteChat: "You cannot delete chat directories.",
      cannotDeleteShared: "You cannot delete shared root directories.",
      createDirectoryFailed: "Failed to create directory.",
      createDirectoryPermissionDenied: "You do not have permission to create a directory in this location.",
      renameFailed: "Failed to rename file.",
      renamePermissionDenied: "You do not have permission to rename this file.",
      copyFailed: "Failed to copy file.",
      cannotCopyDirectory: "You cannot copy a directory.",
      moveFailed: "Failed to move file.",
      movePermissionDenied: "You do not have permission to move this file or folder.",
      restoreHistoryFailed: "Failed to restore file history.",
      restoreHistoryPermissionDenied: "You do not have permission to restore this file history.",
      accessDenied: "You don't have access to this file.",
      folderAccessDenied: "You don't have access to this folder.",
      contentNotFound: "The content to be replaced does not exist in the file.",
      cannotMoveIntoDescendant: "Cannot move a directory into its own descendant.",
      cannotMoveIntoFile: "Cannot move a file/directory into a file.",
      cannotMoveChat: "You cannot move a chat directory.",
    },
  },
  modal: {
    userEdit: {
      title: "Edit User",
      userName: "User Name",
      userNamePlaceholder: "Enter user name",
      language: "Language",
      english: "English",
      japanese: "日本語",
      failed: "Failed",
    },
    userInvite: {
      title: "Invite User",
      emailLabel: "Email",
      emailPlaceholder: "user@workingroom.io",
      invalidEmail: "Please enter a valid email address",
      invite: "Invite",
      failed: "Failed",
    },
    userChangeRole: {
      title: "Edit Tenant",
      userRole: "User Role",
      admin: "Admin",
      member: "Member",
      roleUnchanged: "Role is unchanged",
      failed: "Failed",
    },
    userDelete: {
      title: "Delete User",
      confirm: "Are you sure you want to delete this user?",
      failed: "Failed",
    },
    userResetPassword: {
      title: "Reset User Password",
      confirm: "Are you sure you want to reset the password for this user?",
      failed: "Failed",
    },
    tenantEdit: {
      title: "Edit Tenant",
      tenantName: "Tenant Name",
      tenantNamePlaceholder: "Enter tenant name",
      nameUnchanged: "Name is unchanged",
      failed: "Failed",
    },
    directoryCreate: {
      title: "Create Directory",
      directoryName: "Directory Name",
      directoryNamePlaceholder: "Enter directory name",
      create: "Create",
      failed: "Failed",
    },
    directoryDelete: {
      title: "Delete Directory",
      confirm: "Are you sure you want to delete the directory?",
      allFilesDeleted: "All files under this directory will also be deleted.",
      failed: "Failed",
    },
    fileRename: {
      title: "Rename File",
      fileName: "File Name",
      fileNamePlaceholder: "Enter file name",
      sameAsCurrentName: "Same as current name",
      failed: "Failed",
    },
    fileDelete: {
      title: "Delete File",
      confirmSingular: "Are you sure you want to delete this file?",
      confirmPlural: "Are you sure you want to delete these files?",
      failed: "Failed",
    },
    fileHistoryRestore: {
      title: "Restore File History",
      confirm: "Are you sure you want to restore the file history?",
      failed: "Failed",
    },
    chatDelete: {
      title: "Delete Chat",
      confirm: "Are you sure you want to delete this chat?",
      error: "Error",
    },
    initializePassword: {
      title: "Password Initialization",
      password: "Password",
      passwordPlaceholder: "password",
      confirmPassword: "Confirm Password",
      confirmPasswordPlaceholder: "confirm password",
      passwordMismatch: "Passwords do not match",
      initialize: "Initialize Password",
      error: "Error",
    },
    accessGroupCreate: {
      title: "Create Access Group",
      description: "Creating an access group for {0}.",
      permissionNote: "You can manage the permissions of this group after creation.",
      groupName: "Group Name",
      groupNamePlaceholder: "e.g. Marketing Team",
      groupNameRequired: "Group name is required",
      groupNameMaxLength: "Group name must be less than 50 characters",
      descriptionLabel: "Description (optional)",
      descriptionPlaceholder: "Enter group description",
      success: "Success",
      successMessage: 'Access group "{0}" has been created.',
      failed: "Failed",
    },
    accessGroupDelete: {
      title: "Delete Access Group",
      confirm: "Are you sure you want to delete the following access group?",
      failed: "Failed",
    },
  },
  settingUser: {
    title: "User list",
    description: "Manage your user",
    addUser: "Add User",
    actions: {
      resetPassword: "Reset Password",
      changeRole: "Change Role",
      delete: "Delete",
    },
    headers: {
      name: "Name",
      email: "Email",
      role: "Role",
      createdAt: "Created At",
    },
  },
  settingAccessGroupList: {
    title: "Access Group list",
    description: "Manage organization access groups",
    headers: {
      name: "Name",
      type: "Type",
      description: "Description",
    },
  },
  settingAccessGroup: {
    title: "Access Group Management",
    description: "Manage access group",
    delete: "Delete",
    yes: "Yes",
    no: "No",
    details: {
      title: "Details",
      name: "Name",
      description: "Description",
      type: "Type",
      read: "Read",
      write: "Write",
      personal: "Personal",
      group: "Group",
    },
    resources: {
      title: "Resources in this access group",
      name: "Name",
      type: "Type",
    },
    users: {
      title: "Users in this access group",
      name: "Name",
      email: "Email",
    },
  },
}
