import en from "./en"

export default {
  sidemenu: {
    newChat: "新しいチャット",
    chat: "チャット",
    agents: "エージェント",
    setting: "設定",
    folder: "フォルダ",
    mode: {
      light: "Light",
      dark: "Dark",
    },
  },
  setting: {
    title: "設定",
    description: "組織の設定を管理します",
    organization: {
      title: "組織",
      name: "名前",
    },
    userManagement: {
      title: "ユーザー管理",
      goToList: "ユーザー一覧へ",
    },
    accessGroup: {
      title: "アクセスグループ管理",
      goToList: "アクセスグループ一覧へ",
    },
    agentSettings: {
      title: "エージェント設定",
      name: "名前",
      description: "説明",
      coordinator: {
        name: "Coordinator",
        description: "ユーザー向けエージェント",
      },
      heavy: {
        name: "Heavy",
        description: "深く考えるための高度なモデル",
      },
    },
    tokenUsage: {
      title: "トークン使用量",
      date: "日付",
      model: "モデル",
      inputCached: "入力トークン (キャッシュ)",
      output: "出力トークン",
    },
  },
  account: {
    title: "アカウント",
    description: "ユーザーの設定を管理します",
    userData: {
      title: "ユーザー情報",
      name: "名前",
      email: "メールアドレス",
      role: "権限",
    },
    signout: {
      title: "サインアウト",
      button: "サインアウト",
      error: "サインアウトに失敗しました",
    },
  },
  common: {
    save: "保存",
    cancel: "キャンセル",
    ok: "OK",
    failed: "失敗",
    error: "エラー",
    cannotBeUndone: "この操作は取り消せません。",
    noDataAvailable: "データがありません。",
    goBackToHome: "ホームに戻る",
    loading: "読み込み中...",
    validation: {
      required: "必須項目です",
      passwordMinLength: "パスワードは8文字以上で入力してください",
    },
  },
  errorPage: {
    notFound: "404 Not Found",
    forbidden: "403 Forbidden",
    serverError: "500 Internal Server Error",
  },
  signin: {
    appName: "WorkingRoom",
    title: "サインイン",
    emailLabel: "メールアドレス",
    emailPlaceholder: "メールアドレス",
    passwordLabel: "パスワード",
    passwordPlaceholder: "パスワード",
    submit: "サインイン",
    noAccount: "アカウントをお持ちでない方はこちら",
    failed: "サインインに失敗しました",
  },
  signup: {
    appName: "WorkingRoom",
    title: "サインアップ",
    emailLabel: "メールアドレス",
    emailPlaceholder: "メールアドレス",
    submit: "サインアップ",
    alreadyHaveAccount: "アカウントをお持ちの方はこちら",
    successTitle: "サインアップ完了",
    successCredentials: "認証情報をダウンロードしました。\nダウンロードしたファイルの初期パスワードを確認してサインインしてください。",
    successEmail: "サインインリンクをメールで送信しました。",
    failed: "サインアップに失敗しました",
  },
  home: {
    title: "チャット一覧",
    description: "新しいチャットを開始するか、既存のチャットを続けてください",
    startFirstChat: "最初のチャットを始める",
    newChat: "新しいチャット",
  },
  chat: {
    placeholder: "Chat with your assistant",
    inputPlaceholder: "メッセージを入力してください...",
    moreFileSingular: "他 {0} ファイル",
    moreFilePlural: "他 {0} ファイル",
  },
  tree: {
    description: "ファイルとフォルダを参照します",
    uploadTitle: "アップロード",
    uploadSuccess: "ファイルをアップロードしました。",
    uploadFailed: "ファイルのアップロードに失敗しました。",
    dropToUpload: "ここにファイルをドロップしてアップロード",
  },
  accessGroup: {
    createFailed: "アクセスグループの作成に失敗しました。",
    deleteFailed: "アクセスグループの削除に失敗しました。",
    chatDirNotAllowed: "チャットディレクトリはアクセスグループに追加できません",
    privateDirNotAllowed: "プライベートディレクトリはアクセスグループに追加できません",
    personalGroupNotDeletable: "個人用アクセスグループは削除できません",
  },
  file: {
    backToDirectory: "ディレクトリに戻る",
    createdAt: "{0} 作成",
    noPdfPlugin: "このブラウザにはPDFプラグインがありません。",
    downloadPdf: "こちらからPDFファイルをダウンロードできます。",
    unsupportedFileType: "未対応のファイル形式:",
    notFound: "ファイルが見つかりません",
    history: {
      title: "ファイル履歴",
      loading: "読み込み中...",
      noHistory: "履歴がありません。",
      current: "現在",
    },
    list: {
      noFiles: "ファイルがありません",
      name: "名前",
      type: "種類",
      modified: "更新日時",
      back: "戻る",
      newFolder: "新しいフォルダ",
      rename: "名前変更",
      delete: "削除",
      copyTitle: "コピー",
      copySuccess: "ファイルをコピーしました。",
      moveTitle: "移動",
      moveSuccess: "ファイルを移動しました。",
      moveInvalid: "無効なファイルまたはフォルダです。",
      accessGroup: "アクセスグループを作成",
      dragItems: "{0} 件",
    },
    errors: {
      uploadFailed: "ファイルのアップロードに失敗しました。",
      uploadPermissionDenied: "この場所にファイルをアップロードする権限がありません。",
      uploadToChatFailed: "ファイルをチャットにアップロードしに失敗しました。",
      deleteFailed: "ファイルの削除に失敗しました。",
      cannotDeleteRoot: "ルートディレクトリは削除できません。",
      cannotDeletePrivate: "プライベートディレクトリは削除できません。",
      cannotDeleteChat: "チャットディレクトリは削除できません。",
      cannotDeleteShared: "共有ルートディレクトリは削除できません。",
      createDirectoryFailed: "ディレクトリの作成に失敗しました。",
      createDirectoryPermissionDenied: "この場所にディレクトリを作成する権限がありません。",
      renameFailed: "ファイル名の変更に失敗しました。",
      renamePermissionDenied: "このファイルの名前を変更する権限がありません。",
      copyFailed: "ファイルのコピーに失敗しました。",
      cannotCopyDirectory: "ディレクトリはコピーできません。",
      moveFailed: "ファイルの移動に失敗しました。",
      movePermissionDenied: "このファイルまたはフォルダを移動する権限がありません。",
      restoreHistoryFailed: "ファイル履歴の復元に失敗しました。",
      restoreHistoryPermissionDenied: "このファイル履歴を復元する権限がありません。",
      accessDenied: "このファイルにアクセスする権限がありません。",
      folderAccessDenied: "このフォルダにアクセスする権限がありません。",
      contentNotFound: "置き換える内容がファイルに見つかりません。",
      cannotMoveIntoDescendant: "ディレクトリをその子孫に移動することはできません。",
      cannotMoveIntoFile: "ファイルまたはディレクトリをファイルに移動することはできません。",
      cannotMoveChat: "チャットディレクトリは移動できません。",
    },
  },
  modal: {
    userEdit: {
      title: "ユーザー編集",
      userName: "ユーザー名",
      userNamePlaceholder: "ユーザー名を入力",
      language: "言語",
      english: "English",
      japanese: "日本語",
      failed: "失敗",
    },
    userInvite: {
      title: "ユーザー招待",
      emailLabel: "メールアドレス",
      emailPlaceholder: "user@workingroom.io",
      invalidEmail: "有効なメールアドレスを入力してください",
      invite: "招待",
      failed: "失敗",
    },
    userChangeRole: {
      title: "テナント編集",
      userRole: "ユーザーロール",
      admin: "管理者",
      member: "メンバー",
      roleUnchanged: "ロールが変更されていません",
      failed: "失敗",
    },
    userDelete: {
      title: "ユーザー削除",
      confirm: "このユーザーを削除してもよろしいですか？",
      failed: "失敗",
    },
    userResetPassword: {
      title: "パスワードリセット",
      confirm: "このユーザーのパスワードをリセットしてもよろしいですか？",
      failed: "失敗",
    },
    tenantEdit: {
      title: "テナント編集",
      tenantName: "テナント名",
      tenantNamePlaceholder: "テナント名を入力",
      nameUnchanged: "名前が変更されていません",
      failed: "失敗",
    },
    directoryCreate: {
      title: "ディレクトリ作成",
      directoryName: "ディレクトリ名",
      directoryNamePlaceholder: "ディレクトリ名を入力",
      create: "作成",
      failed: "失敗",
    },
    directoryDelete: {
      title: "ディレクトリ削除",
      confirm: "このディレクトリを削除してもよろしいですか？",
      allFilesDeleted: "このディレクトリ内のすべてのファイルも削除されます。",
      failed: "失敗",
    },
    fileRename: {
      title: "ファイル名変更",
      fileName: "ファイル名",
      fileNamePlaceholder: "ファイル名を入力",
      sameAsCurrentName: "現在のファイル名と同じです",
      failed: "失敗",
    },
    fileDelete: {
      title: "ファイル削除",
      confirmSingular: "このファイルを削除してもよろしいですか？",
      confirmPlural: "これらのファイルを削除してもよろしいですか？",
      failed: "失敗",
    },
    fileHistoryRestore: {
      title: "ファイル履歴の復元",
      confirm: "ファイル履歴を復元してもよろしいですか？",
      failed: "失敗",
    },
    chatDelete: {
      title: "チャット削除",
      confirm: "このチャットを削除してもよろしいですか？",
      error: "エラー",
    },
    initializePassword: {
      title: "パスワードの初期設定",
      password: "パスワード",
      passwordPlaceholder: "パスワード",
      confirmPassword: "パスワード確認",
      confirmPasswordPlaceholder: "パスワード確認",
      passwordMismatch: "パスワードが一致しません",
      initialize: "パスワードを設定",
      error: "エラー",
    },
    accessGroupCreate: {
      title: "アクセスグループを作成",
      description: "{0} に対するアクセスグループを作成します。",
      permissionNote: "作成後にこのグループの権限を管理できます。",
      groupName: "グループ名",
      groupNamePlaceholder: "例: マーケティングチーム",
      groupNameRequired: "グループ名は必須です",
      groupNameMaxLength: "グループ名は50文字以内で入力してください",
      descriptionLabel: "説明（任意）",
      descriptionPlaceholder: "グループの説明を入力",
      success: "成功",
      successMessage: 'アクセスグループ "{0}" を作成しました。',
      failed: "失敗",
    },
    accessGroupDelete: {
      title: "アクセスグループを削除",
      confirm: "以下のアクセスグループを削除してもよろしいですか？",
      failed: "失敗",
    },
    agentDelete: {
      title: "エージェント削除",
      confirm: 'エージェント "{0}" を削除してもよろしいですか？',
      failed: "エージェントの削除に失敗しました",
    },
    fileSelect: {
      title: "フォルダ選択",
      name: "名前",
      back: "戻る",
      noFiles: "ファイルがありません",
      select: "選択",
      close: "閉じる",
    },
  },
  settingUser: {
    title: "ユーザー一覧",
    description: "ユーザーを管理します",
    addUser: "ユーザーを追加",
    actions: {
      resetPassword: "パスワードリセット",
      changeRole: "権限変更",
      delete: "削除",
    },
    headers: {
      name: "名前",
      email: "メールアドレス",
      role: "権限",
      createdAt: "作成日時",
    },
  },
  settingAccessGroupList: {
    title: "アクセスグループ一覧",
    description: "組織のアクセスグループを管理します",
    headers: {
      name: "名前",
      type: "種類",
      description: "説明",
    },
  },
  settingAccessGroup: {
    title: "アクセスグループ管理",
    description: "アクセスグループを管理します",
    delete: "削除",
    yes: "Yes",
    no: "No",
    details: {
      title: "詳細",
      name: "名前",
      description: "説明",
      type: "種類",
      read: "読み取り",
      write: "書き込み",
      personal: "個人",
      group: "グループ",
    },
    resources: {
      title: "このアクセスグループのリソース",
      name: "名前",
      type: "種類",
    },
    users: {
      title: "このアクセスグループのユーザー",
      name: "名前",
      email: "メールアドレス",
    },
  },
  agent: {
    list: {
      title: "エージェント一覧",
      description: "作成したエージェントのリスト",
      name: "名前",
      tier: "ティア",
      noData: "-",
      create: "作成",
      delete: "削除",
    },
    create: {
      title: "エージェント作成",
      description: "ワークスペース用の新しいエージェントを作成します。",
      success: "成功",
      created: "エージェントを作成しました",
      sectionDescriptions: "エージェント説明",
      sectionPrompt: "プロンプト",
      fields: {
        name: "名前",
        namePlaceholder: "例: 会社ルールエージェント",
        tier: "モデルティア",
        workingFolder: "作業フォルダ",
        workingFolderPlaceholder: "作業フォルダを選択",
        description: "説明",
        descriptionPlaceholder: "例: 会社ルールの管理を支援するエージェント",
        descriptionForAgent: "エージェント向け説明",
        descriptionForAgentPlaceholder: "例: 会社ルールの管理を支援するエージェント",
        prompt: "システムプロンプト",
        promptPlaceholder: "例: 会社ルールの要約を生成してください",
      },
      validation: {
        nameRequired: "名前は必須です",
        nameMaxLength: "名前は50文字以内で入力してください",
        descriptionForAgentRequired: "エージェント向け説明は必須です",
        promptRequired: "システムプロンプトは必須です",
        tierRequired: "モデルティアは必須です",
        tierInvalid: "無効なモデルティアです",
        descriptionMaxLength: "説明は200文字以内で入力してください",
      },
    },
    detail: {
      title: "エージェント",
      defaultDescription: "エージェント詳細",
      edit: "編集",
      sectionDescriptions: "エージェント説明",
      sectionDescriptionForAgent: "エージェント向け説明",
      sectionPrompt: "システムプロンプト",
      fields: {
        name: "名前",
        tier: "モデルティア",
        workingFolder: "作業フォルダ",
        description: "説明",
        noData: "-",
      },
    },
    edit: {
      title: "エージェント編集",
      description: "エージェント設定を更新します。",
      updated: "エージェントを更新しました",
      save: "保存",
    },
  },
} satisfies typeof en
