import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

const sidebars: SidebarsConfig = {
  docs: [
    "index",
    { type: "category", label: "Getting Started", items: [{ type: "autogenerated", dirName: "getting-started" }] },
    { type: "category", label: "User Guide", items: [{ type: "autogenerated", dirName: "user-guide" }] },
    { type: "category", label: "Development", items: [{ type: "autogenerated", dirName: "development" }] },
    "roadmap/index",
    "faq/index",
  ],
}

export default sidebars
